apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-crossplane-operator
spec:
  template:
    spec:
      containers:
      - env:
        - name: IBM_CROSSPLANE_IMAGE
          value: "hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/ibm-crossplane:1.0.0-beta"
        name: ibm-crossplane-operator
        image: "hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/ibm-crossplane-operator-amd64:dev"