---
apiVersion: operator.ibm.com/v1beta1
kind: Crossplane
metadata:
  labels:
    app.kubernetes.io/instance: ibm-crossplane
    app.kubernetes.io/managed-by: ibm-crossplane-operator
    app.kubernetes.io/name: ibm-crossplane-operator
  name: ibm-crossplane
spec:
  configuration:
    packages:
    - hyc-cloud-private-daily-docker-local.artifactory.swg-devops.com/ibmcom/ibm-crossplane-bedrock-shim-config:1.0.0
    packagePullSecrets:
    - artifactory-secret
  defaultLabel:
    name: provider
    value: odlm
  replicas: 1
  resourcesCrossplane:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi